version: '3.8'

services:
  db:
    image: postgres:13
    container_name: joyeria_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 3gL9qbjeorcLUj9IQMir77maMA2wetig
      POSTGRES_DB: joyeria_ja8q
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d joyeria_ja8q"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: joyeria_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@joyeria.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    build: .
    container_name: joyeria_web
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://joyeria_user:joyeria_pass@db:5432/joyeria_db
      FLASK_ENV: production
    volumes:
      - .:/app

volumes:
  postgres_data:
  pgadmin_data: